### ISSUE TITLE
Make Ywar update configurable

### ISSUE THREAD

**Issue by frioux** [rjbs/Ywar#3]
Frew's original suggestion:

``` yaml
[{
   plugin: Rubric
   checks:
      journal.any:
         method: posted_new_entry
         tdp_id: 334
},{
   plugin: Maildir
   checks:
      mail.flagged:
         method: decreasing_flagged_mail
         tdp_id: 45660
      mail.unread:
         method: decreasing_unread_mail
         tdp_id: 333
      p5p.changes:
         method: folder_old_unread
         tdp_id: 325
         args: [{ age: 259200, folder => '/INBOX/perl/changes' }],
      p5p.unread:
         method: folder_old_unread
         tdp_id: 328
         args: [{ age: 1209600, folder => '/INBOX/perl/p5p' }],
}]
```
